name: OrthoFinder
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "dev-*"
      - "feat/**"
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
      - 'DEVNOTES.md'
      - 'CONTRIBUTING.md'
      - 'CONDUCT.md'
  pull_request:
    branches:
      - "master"
      - "dev_*"
      - "feat/**"
    types:
      - opened
    paths-ignore:
      - ".github/workflows/*"

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - name: Get Code
      uses: actions/checkout@v4

    - name: Load & Cache Dependencies
      id: cache-dependencies
      uses: ./.github/actions/cached-dependencies
      with:
        caching: 'true' # default

    - name: Output information
      run: |
        echo "Cache used? ${{ steps.cache-dependencies.outputs.used-cache}}"

    - name: Test screen printout
      run: python recur.py

  test:
    needs: build
    continue-on-error: true
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}

    steps:
    - name: Get Code
      uses: actions/checkout@v4

    - name: Load & Cache Dependencies
      id: cache-dependencies
      uses: ./.github/actions/cached-dependencies
      with:
        caching: 'true' # default

    - name: Output information
      run: |
        echo "Cache used? ${{ steps.cache-dependencies.outputs.used-cache}}"

    - name: Activate conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        use-mamba: true  # Optional for faster installs

    - name: Install Conda Dependencies
      run: |
        conda install bioconda::diamond -y
        conda install bioconda::mcl -y
        conda install bioconda::famsa -y
        conda install bioconda::fasttree -y
        mcl --version
        diamond --version  # Check if diamond is installed correctly
        iqtree2 --version  # Check if iqtree2 is installed correctly

    - name: Test OrthoFinder on ExampleData
      run: |
        python3 orthofinder.py -f ExampleData -efn
        
    # - name: Test with pytest
    #   run: |
    #     pytest -m regression -sv  tests/test_reconfig --no-cov
